# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65629c68ba6eb946ca48ca399dd98666f8ec43844ea4e0ed84c4731c677699df1d39b32e1da5152b96cbf9d6ac92e782c6a91af24ad2592a13a8cc46865eb005

test:
  secret_key_base: abce0c6865a9e40de6ca6ecaaab52ca3fafb04074b303bb207e3fe0ddf7ee0ce98c6460c5d2830fce88f636641b373baa7e33bddef2bda38332cd8dd0c2e9d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
